### ISSUE TITLE
How to create a visualization similar to Figure 4 in the paper.

### ISSUE THREAD

**Issue by cpy0029** [wurenkai/UltraLight-VM-UNet#19]
How do I create a visualization similar to Figure 4, including for models such as UltraLightVM-Unet, LightM-Unet, VM-UNet, and others?

Thanks!!!

**Comment by wurenkai** [comment]
Hi, our model generates visualized segmentation plots (original at the top, Ground Truth in the middle, and predicted at the bottom) in 'outputs' in the 'results' folder after both training and testing. And the formation of Figure 4 requires some post-processing (cut and merge) to form.
