### ISSUE TITLE
about training speed

### ISSUE THREAD

**Issue by duanyifei777** [wurenkai/UltraLight-VM-UNet#7]
I'd like to ask about training speed, I'm running an epoch on a windows 4090 for about 5 minutes, I feel like it's a little slow, is that normal? My dataset size is only a quarter of the size of isic17.

**Comment by wurenkai** [comment]
Hi, 5 minutes training time is not normal. It takes me less than half a minute to train an epoch on the ISIC2017 dataset. Also, your data size is a quarter of the ISIC2017 dataset.
![1](https://github.com/wurenkai/UltraLight-VM-UNet/assets/124028634/80384b4b-f5db-450e-a944-4cb9e2112628)

You can check to see if the parameters and GFLOPs are as expected by changing the following code in 'train.py'.
```
    print('#----------Prepareing Models----------#')
    model_cfg = config.model_config
    model = UltraLight_VM_UNet(num_classes=model_cfg['num_classes'], 
                               input_channels=model_cfg['input_channels'], 
                               c_list=model_cfg['c_list'], 
                               split_att=model_cfg['split_att'], 
                               bridge=model_cfg['bridge'],)
    model = model.cuda()

    cal_params_flops(model, 256, logger) # 256 is the size of the input model image, change as desired.
    #model = torch.nn.DataParallel(model.cuda(), device_ids=gpu_ids, output_device=gpu_ids[0])

```

**Comment by duanyifei777** [comment]
Ok, thanks, my parameters and complexity are normal, I think it's because I'm on windows, I'll try to run it on Linux.
